import { mkdir } from "node:fs/promises";
import { expect, test } from "@playwright/test";

/**
 * Responsive evidence for the acceptance checklist. Files land in
 * mobile/screenshots/ and are regenerated by `npm run test:e2e`.
 */

const VIEWPORTS = [
  { name: "320x700", width: 320, height: 700 },
  { name: "390x844", width: 390, height: 844 },
  { name: "430x932", width: 430, height: 932 },
  { name: "768-tablet", width: 768, height: 1024 },
];

const SCREENS = [
  { slug: "today", path: "/" },
  { slug: "briefing", path: "/briefing" },
  { slug: "requests", path: "/requests" },
  { slug: "request-detail", path: "/requests/req-301" },
  { slug: "spaces", path: "/spaces" },
  { slug: "space-detail", path: "/spaces/space-roca-llisa" },
  { slug: "gates", path: "/gates" },
  { slug: "dues", path: "/dues" },
  { slug: "experiences", path: "/experiences" },
  { slug: "experience-detail", path: "/experiences/exp-501" },
  { slug: "people", path: "/people" },
  { slug: "person-360", path: "/people/person-ana-martins" },
  { slug: "vendors", path: "/vendors" },
  { slug: "more", path: "/more" },
  { slug: "settings", path: "/settings" },
  { slug: "design-system", path: "/design-system" },
];

const DIR = "screenshots";

test.beforeAll(async () => {
  await mkdir(DIR, { recursive: true });
});

test.describe("responsive screenshots", () => {
  for (const vp of VIEWPORTS) {
    test(`captures ${vp.name}`, async ({ page }, testInfo) => {
      // The viewport matrix is captured once, by the default project.
      test.skip(testInfo.project.name !== "phone-390", "captured by phone-390");
      await page.setViewportSize({ width: vp.width, height: vp.height });

      for (const screen of SCREENS) {
        await page.goto(screen.path);
        await page.waitForTimeout(350);

        // No screen may overflow horizontally at any required width.
        const overflow = await page.evaluate(
          () => document.documentElement.scrollWidth > window.innerWidth + 1,
        );
        expect(overflow, `${screen.path} overflows at ${vp.name}`).toBe(false);

        await page.screenshot({ path: `${DIR}/${vp.name}__${screen.slug}.png` });
      }
    });
  }

  test("captures the open states", async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== "phone-390", "captured by phone-390");
    await page.setViewportSize({ width: 390, height: 844 });

    await page.goto("/");
    await page.getByTestId("add-fab").click();
    await expect(page.getByTestId("composer-sheet")).toBeVisible();
    await page.waitForTimeout(400);
    await page.screenshot({ path: `${DIR}/390x844__composer-sheet.png` });
    await page.keyboard.press("Escape");

    await page.getByTestId("collecta-orb").click();
    await expect(page.getByTestId("collecta-sheet")).toBeVisible();
    await page.waitForTimeout(400);
    await page.screenshot({ path: `${DIR}/390x844__collecta-sheet.png` });
    await page.keyboard.press("Escape");

    await page.goto("/requests");
    await page.getByTestId("request-row").first().click();
    await expect(page.getByTestId("detail-sheet")).toBeVisible();
    await page.waitForTimeout(300);
    await page.screenshot({ path: `${DIR}/390x844__detail-sheet.png` });

    await page.getByTestId("approve-request").click();
    await expect(page.getByTestId("confirm-sheet")).toBeVisible();
    await page.waitForTimeout(300);
    await page.screenshot({ path: `${DIR}/390x844__confirm-sheet.png` });
  });

  test("captures every load state", async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== "phone-390", "captured by phone-390");
    await page.setViewportSize({ width: 390, height: 844 });
    for (const scenario of ["empty", "loading", "error", "offline", "busy"]) {
      await page.goto(`/?scenario=${scenario}`);
      await page.waitForTimeout(300);
      await page.screenshot({ path: `${DIR}/390x844__today-${scenario}.png` });
    }
  });
});

test.describe("reduced motion evidence", () => {
  test("captures reduced-motion Today", async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== "reduced-motion-390", "reduced-motion project only");
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto("/");
    await page.waitForTimeout(350);
    await page.screenshot({ path: `${DIR}/reduced-motion-390x844__today.png` });
  });
});
